"""Removed unique constraints from property table

Revision ID: 913248554d44
Revises: 
Create Date: 2025-10-02 12:35:24.604233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913248554d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('rent_collection_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('property_features',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('property_Land_no_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('property_Location_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('property_Units_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('property_caretaker_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('property_caretaker_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('property_security_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('property_security_name_key'), ['security_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('property_caretaker_key'), ['caretaker'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('property_caretaker_id_key'), ['caretaker_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('property_Units_key'), ['Units'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('property_Location_key'), ['Location'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('property_Land_no_key'), ['floors'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('property_features',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('rent_collection_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
