"""remove unique constraints from Tenant

Revision ID: d92b6541ac13
Revises: 913248554d44
Create Date: 2025-10-08 10:03:06.211291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92b6541ac13'
down_revision = '913248554d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Tenant_apartment_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_bedrooms_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_children_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_deposit_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_employment_status_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_family_size_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_house_condition_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_housemanager_ID_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_housemanager_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_housenumber_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_identification_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_nationality_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_phonenumber_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_reference_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_reference_phone_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_rent_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_tenantemail_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Tenant_tenantname_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('Tenant_tenantname_key'), ['tenantname'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_tenantemail_key'), ['tenantemail'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_rent_key'), ['rent'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_reference_phone_key'), ['reference_phone'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_reference_name_key'), ['reference_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_phonenumber_key'), ['phonenumber'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_nationality_key'), ['nationality'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_identification_number_key'), ['identification_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_housenumber_key'), ['housenumber'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_housemanager_name_key'), ['housemanager_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_housemanager_ID_key'), ['housemanager_ID'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_house_condition_key'), ['house_condition'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_family_size_key'), ['family_size'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_employment_status_key'), ['employment_status'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_deposit_key'), ['deposit'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_children_key'), ['children'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_bedrooms_key'), ['bedrooms'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Tenant_apartment_name_key'), ['apartment_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
